/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BranchingDrawer {
        "branchFour": any;
        "branchOne": any;
        "branchThree": any;
        "branchTwo": any;
        "branchingNumber": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBranchingDrawerElement extends Components.BranchingDrawer, HTMLStencilElement {
    }
    var HTMLBranchingDrawerElement: {
        prototype: HTMLBranchingDrawerElement;
        new (): HTMLBranchingDrawerElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "branching-drawer": HTMLBranchingDrawerElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BranchingDrawer {
        "branchFour"?: any;
        "branchOne"?: any;
        "branchThree"?: any;
        "branchTwo"?: any;
        "branchingNumber"?: number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "branching-drawer": BranchingDrawer;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "branching-drawer": LocalJSX.BranchingDrawer & JSXBase.HTMLAttributes<HTMLBranchingDrawerElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
